# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: test-e2e
test-e2e:
	@./cicd-scripts/run-e2e-tests.sh
