
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - searchoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - searchoperators/status
  verbs:
  - get
  - patch
  - update
