# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
# permissions for end users to view searchcustomizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: searchcustomization-viewer-role
rules:
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - searchcustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - searchcustomizations/status
  verbs:
  - get
