apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: searchoperators.search.open-cluster-management.io
spec:
  group: search.open-cluster-management.io
  names:
    kind: SearchOperator
    listKind: SearchOperatorList
    plural: searchoperators
    singular: searchoperator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SearchOperator is the Schema for the searchoperators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SearchOperatorSpec defines the desired state of SearchOperator
          properties:
            customlabelselector:
              type: string
            customlabelvalue:
              type: string
            limit_cpu:
              description: Limit CPU
              type: string
            limit_memory:
              description: Limit Memory
              type: string
            nodeselector:
              type: boolean
            nodeselectoros:
              type: string
            persistence:
              type: boolean
            pullpolicy:
              type: string
            pullsecret:
              type: string
            redisgraph_image:
              description: Image to use in deployment
              type: string
            request_cpu:
              description: Request CPU
              type: string
            request_memory:
              description: Request memory
              type: string
            storageclass:
              type: string
            storagesize:
              type: string
          required:
          - limit_cpu
          - limit_memory
          - pullpolicy
          - pullsecret
          - redisgraph_image
          - request_cpu
          - request_memory
          type: object
        status:
          description: SearchOperatorStatus defines the observed state of SearchOperator
          properties:
            persistence:
              type: string
          required:
          - persistence
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
