# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: search-operator
subjects:
- kind: ServiceAccount
  namespace: open-cluster-management
  name: search-operator
roleRef:
  kind: ClusterRole
  name: search-operator
  apiGroup: rbac.authorization.k8s.io
