# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: search-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
- apiGroups:
  - "apps"
  resources:
  - "*" 
  verbs:
  - get
- apiGroups:
  - "search.acm.com"
  - "search.open-cluster-management.io"
  resources:
  - "*"
  verbs:
  - "*"
