apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: search-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - 'deployments'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch 
- apiGroups:
  - search.acm.com
  - search.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - delete