# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchOperator
metadata:
  name: searchoperator
spec:
  # Add fields here
  redisgraph_resource:
    limit_memory: 1Gi
    request_cpu: 25m
    request_memory: 64Mi
  pullpolicy: Always
  pullsecret: multiclusterhub-operator-pull-secret
  searchimageoverrides:
    redisgraph_tls: quay.io/stolostron/redisgraph-tls:2.4.0-fa4d8aeed0c1f9b5bd9e118d85538dcd787c26b1